[phases.setup]
nixPkgs = ["nodejs_24"]

[phases.install]
cmds = ["npx --yes pnpm@11.9.0 install --frozen-lockfile"]

[phases.build]
cmds = ["npx --yes pnpm@11.9.0 --filter @workwear/client build"]

[start]
cmd = "npx --yes pnpm@11.9.0 db:migrate && npx --yes pnpm@11.9.0 db:seed && npx --yes pnpm@11.9.0 --filter @workwear/server start"
