import { z } from 'zod';
import { atomicSizeOfType, compareSizes } from '../../catalogs/model/size-options.js';

const emptyToUndefined = (value) => (value === '' ? undefined : value);
const optionalUuid = z.preprocess(emptyToUndefined, z.string().uuid().optional());
const optionalDate = z.preprocess(emptyToUndefined, z.string().date().optional());
const optionalString = (max) => z.preprocess(emptyToUndefined, z.string().max(max).optional());

export const GENDER_LABELS = { male: 'Мужской', female: 'Женский' };

export const employeeFormSchema = z.object({
  organizationId: z.string().uuid('Выберите организацию'),
  subdivisionId: optionalUuid,
  positionId: optionalUuid,
  dpoId: optionalUuid,
  fullName: z.string().min(1, 'Укажите ФИО').max(255),
  gender: z.preprocess(emptyToUndefined, z.enum(['male', 'female']).optional()),
  personnelNumber: optionalString(64),
  birthDate: optionalDate,
  hireDate: optionalDate,
  terminationDate: optionalDate,
  clothingSizeId: optionalUuid,
  heightSizeId: optionalUuid,
  shoeSizeId: optionalUuid,
  headwearSizeId: optionalUuid,
  beltSizeId: optionalUuid,
  glovesSizeId: optionalUuid,
  phone: optionalString(32),
});

export const employeeFormFields = [
  {
    name: 'organizationId',
    label: 'Организация',
    type: 'select',
    optionsResource: 'organizations',
    optionValue: 'id',
    optionLabel: 'name',
  },
  {
    name: 'subdivisionId',
    label: 'Станция',
    type: 'select',
    optionsResource: 'subdivisions',
    optionValue: 'id',
    optionLabel: 'name',
  },
  {
    name: 'positionId',
    label: 'Должность',
    type: 'select',
    optionsResource: 'positions',
    optionValue: 'id',
    optionLabel: 'name',
  },
  {
    name: 'dpoId',
    label: 'ДПО',
    type: 'select',
    optionsResource: 'dpo',
    optionValue: 'id',
    optionLabel: 'name',
    searchable: true,
    serverSearch: true,
    placeholder: 'Введите название ДПО…',
  },
  { name: 'fullName', label: 'ФИО', type: 'text' },
  {
    name: 'gender',
    label: 'Пол',
    type: 'select',
    options: Object.entries(GENDER_LABELS).map(([value, label]) => ({ value, label })),
  },
  { name: 'personnelNumber', label: 'Табельный номер', type: 'text' },
  { name: 'hireDate', label: 'Дата приёма', type: 'date' },
  { name: 'terminationDate', label: 'Дата увольнения', type: 'date' },
  {
    name: 'clothingSizeId',
    label: 'Размер одежды',
    type: 'select',
    optionsResource: 'sizes',
    optionsFilter: atomicSizeOfType('clothing'),
    optionsSort: compareSizes,
    optionValue: 'id',
    optionLabel: 'value',
  },
  {
    name: 'heightSizeId',
    label: 'Рост',
    type: 'select',
    optionsResource: 'sizes',
    optionsFilter: atomicSizeOfType('height'),
    optionsSort: compareSizes,
    optionValue: 'id',
    optionLabel: 'value',
  },
  {
    name: 'shoeSizeId',
    label: 'Размер обуви',
    type: 'select',
    optionsResource: 'sizes',
    optionsFilter: atomicSizeOfType('shoe'),
    optionsSort: compareSizes,
    optionValue: 'id',
    optionLabel: 'value',
  },
  {
    name: 'headwearSizeId',
    label: 'Размер головного убора',
    type: 'select',
    optionsResource: 'sizes',
    optionsFilter: atomicSizeOfType('headwear'),
    optionsSort: compareSizes,
    optionValue: 'id',
    optionLabel: 'value',
  },
  {
    name: 'beltSizeId',
    label: 'Размер ремня',
    type: 'select',
    optionsResource: 'sizes',
    optionsFilter: atomicSizeOfType('belt'),
    optionsSort: compareSizes,
    optionValue: 'id',
    optionLabel: 'value',
  },
  {
    name: 'glovesSizeId',
    label: 'Размер перчаток',
    type: 'select',
    optionsResource: 'sizes',
    optionsFilter: atomicSizeOfType('gloves'),
    optionsSort: compareSizes,
    optionValue: 'id',
    optionLabel: 'value',
  },
  { name: 'phone', label: 'Телефон', type: 'text' },
];
